config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :posts do
    resources :comments
  end
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  
  root to: "posts#index"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates  :body, presence: true
  has_many :comments
  belongs_to :user
  acts_as_taggable
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_attached_file :project_img, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/assets/user.png"
    validates_attachment_content_type :project_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  
  def create
    @comment = @post.comments.create(comment_params)
    @comment.save
    
    if @comment.save
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
    
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
  
    def find_post
    @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page],:per_page => 4).order('created_at DESC')
    else
      #@posts = Post.all.order('created_at DESC')
      @posts = Post.paginate(:page => params[:page], :per_page => 4).order('created_at DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post).order('created_at DESC')
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :user_id, :project)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :body, :main_img, :project_img, :user_id, :git,:website,:techno)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML 
    def block_code(code, language) 
      Pygments.highlight(code, lexer: language) 
    end
  end
    
    def markdown(content) 
      renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true) 
      options = { 
        autolink: true, 
        no_intra_emphasis: true, 
        disable_intended_code_blocks: true, 
        fenced_code_blocks: true, 
        lax_html_blocks: true, 
        strikethrough: true, 
        superscript: true 
        } 
      Redcarpet::Markdown.new(renderer,options).render(content).html_safe 
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<h2>Comments</h2>  
<% @comments.each do |comment| %>  

<div class="row" id="commenter">
 <div class="col-md-3" id="pencil">
  <%= image_tag("speech-bubble.png")%><%= comment.commenter %> 
 </div>
<div class="col-md-9">
  <strong>Comment:</strong>
  <div id="comments">
    <p><%= markdown(comment.body) %></p> 
  </div>
</div>
</div>  


<% end %>  

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<h2>Add a comment:</h2> 
<%= form_for([@post, @post.comments.build] ) do |f| %>   
<div class="form-group">
  <%= f.label :commenter %><br> 
  <%= f.text_field :commenter %> 
</div> 
<div class="form-group">
  <%= f.label :body %><br> 
  <%= f.text_area :body, class:"form-control" %> 
</div>
<div class="form-group">
 <% if user_signed_in? %>
  <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div> 
<% end %> 

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-6">
      <p >Crafted with <span id='heart-img'><%= image_tag("001-heart.png") %></span> and <span id="ruby-logo"><%= image_tag("ruby.png")%></span> in Valbonne City.
    </div>
    <div class="col-md-6" id="footer-tag">
    <span class="social-media"><%= link_to image_tag("002-social-media.png"), "https://twitter.com/macciak" %></span>
    <span class="social-media"><%= link_to image_tag("003-linkedin.png"), "https://www.linkedin.com/in/alexandrecalice/" %></span>
    <span class="social-media"><%= link_to image_tag("001-github.png"), "https://github.com/gosherama/" %></span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="nav">
  <div class="left-nav">
    <i class="material-icons" id="icon-gesture">gesture</i>
   <p id="tagline"><%= link_to "A coding Journey....", root_path %></p>
  </div>

  <div class="right-nav">
      <% if !current_user %>
        <%= link_to "Blog", root_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
      <% else %>
        <%= link_to "Blog", root_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    
<!--    <ul>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Me</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Posts Admin</a>
            <a class="dropdown-item" href="#">Portfolio Admin</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Sign Out</a>
      </li>
    </ul> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111332131-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-111332131-1');
    </script>    
  </head>

<body>
<div class="container">

<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p> 
<p class="alert"><%= alert %></p> 
  <%= yield %>

<%= render 'layouts/footer' %>
     
</div>   
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= form.label :tag_list, "Tags (Separated by commas)" %>
  <%= form.text_field :tag_list, class:"form-control" %>
</div>
<div class="form-group">
  <%= form.label :project %>
  <%= form.text_field :project, class:"form-control" %>
</div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %W[sm me lg xl] do |tag, css_class| %>
  <%= link_to tag.name.upcase , tag_path(tag.name), class: css_class %>
  <% end %>
</div>
<br>
 <% if user_signed_in? %>
    <%= link_to 'New Post', new_post_path, class:"btn btn-primary btn-sm" %>
  <% end %>
<br>
<br>

<% @posts.each do |post| %>
  <div class = "row">
    <div class="col-md-8">
      <h2> <%= post.title %> </h2>
    </div>
    <div class="col-md-8 flex-icon">
      <h3 id="post-author"><%= image_tag("user.png") %><%= post.user.email %>
      <h3 id="post-date" ><%= image_tag("clock.png") %><%= post.created_at.strftime('%d/%m/%Y') %>
    </div>
    <div class="col-md-10">
      <p id="index-post-content"> <%= markdown truncate(post.body,length: 400) %> </p>
    </div>
    <div class="col-md-10 btn-control">
    <%= link_to 'Show', post, class:"btn btn-primary btn-sm", id:"show-btn" %>
      <% if user_signed_in? %>
        <% if current_user.id === post.user_id %>
          <%= link_to 'Edit', edit_post_path(post), class:"btn btn-warning btn-sm", id:"edit-btn"%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>
        <% end %>
      <% end %>
    </div>
    <hr class="content-separation"/>
    <div class="col-md-8 bio-icons">
      <h3 id="tags"><%= image_tag("settings.png")%><%= post.tag_list.join(' ').upcase %></h3>
    </div>
    <div class="col-md-8 bio-icons">
      <h3 id="post-project-img"><%= image_tag("idea.png") %><%= post.project %></h3>
  </div>
    <br />
    <br />
  </div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-3" id="post-data">
    <h2 id="post-title"><%= @post.title %></h2>
    <h3 id="post-author"><%= image_tag("user.png")%><%= @post.user.email %></h3>
    <h3 id="post-date"><%= image_tag("clock.png")%><%= @post.created_at.strftime('%d/%m/%Y')%></h3>
    <h3 id="tags"><%= image_tag("settings.png")%><%= @post.tag_list.join(' ').upcase %></h3>
    <h3 id="post-project-img"><%= image_tag("idea.png") %><%= @post.project %></h3>
  </div>
  <div class="col-md-9">
    <div id="post-content">
      <%= markdown @post.body %>
    </div>
  </div>
</div>

<%= render 'comments/comment' %>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-primary btn-sm" %>
<% end %>

<%= link_to 'Back', posts_path, class:"btn btn-warning btn-sm" %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :project_body, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :project_img %>
    <%= form.file_field :project_img, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :techno %>
    <%= form.text_field :techno, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :git %>
    <%= form.text_field :git, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="index-title">Projects</h1>

 <% if user_signed_in? %>
  <%= link_to 'New Project', new_project_path, class:"btn btn-primary" %>
<% end %>


  <div class="project-container">
   <% @projects.each do |project| %>
    <div class="project">
       <div id="index-project-title">
         <%= project.title %>
       </div>
       <div id="project-create-date-index">
         Created: <%= project.created_at.strftime('%d/%m/%Y')%>
       </div>
       <div>
         <p><%= markdown truncate(project.body, length:300) %></p>
       </div>
<!--
        <div id="index-project-img">
          <%#= image_tag project.project_img.url(:thumb) %>
        </div>
-->
        <div class="project-techno">
           <%= image_tag("techno.png")%><%= project.techno %>
         </div>
        <div>
        <%= link_to 'Show', project, class:"btn btn-primary btn-sm" %>
        <% if user_signed_in? %>
          <% if current_user.id === project.user_id %>
            <%= link_to 'Edit', edit_project_path(project), class:"btn btn-warning btn-sm" %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-sm" %>
          <% end %>
        <% end %>
        </div>
    </div>
  <% end %>
  </div>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <p id="title"><%= @project.title %></p>
    <h3 id="project-create-date">Created: <%= @project.created_at.strftime('%d/%m/%Y') %></h3>
    <div id="project_img">
      <%= image_tag @project.project_img.url(:thumb) %>  
    </div>
    <div class="project-techno">
      <%= image_tag("techno.png")%><%= @project.techno %>  
    </div>
    <div id="project_git" id="project-www">
      <%= link_to image_tag("github-logo.png"), @project.git %><%= link_to image_tag("web.png"), @project.website %></div>
  </div>
  <div class="col-md-8">
   <div id="project-content">
      <%= image_tag("menu.png") %>
      <%= markdown @project.body %>
   </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project), class:"btn btn-primary btn-sm" %>
<% end %>

<%= link_to 'Back', projects_path, class:"btn btn-warning btn-sm" %>